### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by 5tratz** [Squizy1722/qb-invoices#1]
Hey mate, thanks so much for this script, I have intergrated it to work in my radialmenu, but there is one problem. When I am in the dialogue and I write nothing (ie cancel or want to get out of it) there is this error (img attached)

Would it be possible to add a option (button) on the dialogue part to go back or even cancel?

TIA :)

![Screenshot_5](https://user-images.githubusercontent.com/2183651/194517762-b90efbae-844a-43b9-8f79-73a59a59189b.png)

**Comment by Squizy1722** [comment]
**should be fixed now**
tell me if all good now

**Comment by 5tratz** [comment]
Perfect! fixed, thank you mate :)

**Comment by Squizy1722** [comment]
:)
